export const SET_DATA = 'SET_DATA';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const ADD_SELECTED_ITEM = 'ADD_SELECTED_ITEM';
export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM';
export const TOGGLE_EXPAND_ITEM = 'TOGGLE_EXPAND_ITEM';
export const SET_SEARCH = 'SET_SEARCH';
